apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft-aks
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-aks
    spec:
      containers:
      - name: minecraft-aks
        image: openhack/minecraft-server
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon  
        env:
        - name: EULA
          value: "true"
        
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-aks
spec:
  type: LoadBalancer
  ports:
  - port: 25565
  selector:
    app: minecraft-aks
