apiVersion: v1
kind: Pod
metadata:
  name: apibackend
  labels:
     app: apibackend
spec:
  containers:
    - name: backend
      image: registrotime4openhack.azurecr.io/backend:23
  imagePullSecrets:
    - name: onedasecret
--
apiVersion: v1
kind: Service
metadata:
   name: apibackend
spec:
   type: LoadBalancer
   selector:
      app: apibackend
   ports:
   - port: 80
       
